version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

commands:
  prepare_node:
    steps:
      - run:
         command: yarn install
         working_directory: chrome

jobs:
  install_dependency:
    executor: node-executor
    steps:
      - checkout
      - prepare_node
      - persist_to_workspace:
          root: .
          paths:
            - .

  chrome_lint:
    executor: node-executor
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: .
      - run:
         command: yarn lint
         working_directory: chrome

  chrome_build:
    executor: node-executor
    steps:
      - attach_workspace: # workspaceをアタッチする
          at: .
      - run:
          command: yarn build
          working_directory: chrome

workflows:
  chrome_ci:
    jobs:
      - install_dependency
      - chrome_lint:
          requires:
            - install_dependency
      - chrome_build:
          requires:
            - install_dependency