name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      working-directory: chrome
      run: |
        yarn install
      env:
        CI: true
    - name: npm build
      working-directory: chrome
      run: |
        yarn build
      env:
        CI: true
    - name: npm test
      working-directory: chrome
      run: yarn test
      env:
        CI: true
